#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0  TRIEDGE   float   x   
// SV_TessFactor            1   x           1  TRIEDGE   float   x   
// SV_TessFactor            2   x           2  TRIEDGE   float   x   
// SV_InsideTessFactor      0   x           3   TRIINT   float   x   
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// XETESSFACTOR             0   x           0     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// XEVERTEXID               0   x           0     NONE   float   x   
//
hs_5_1
hs_decls 
dcl_input_control_point_count 3
dcl_output_control_point_count 1
dcl_tessellator_domain domain_tri
dcl_tessellator_partitioning partitioning_fractional_even
dcl_tessellator_output_primitive output_triangle_cw
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[0:0][2], immediateIndexed, space=0
hs_control_point_phase 
dcl_input vPrim
dcl_output o0.x
dcl_temps 1
iadd r0.x, vPrim, CB0[0][1].y
and r0.x, r0.x, l(0x00ffffff)
umax r0.x, r0.x, CB0[0][1].z
umin r0.x, r0.x, CB0[0][1].w
utof o0.x, r0.x
ret 
hs_fork_phase 
dcl_hs_fork_phase_instance_count 3
dcl_input vForkInstanceID
dcl_input vicp[3][0].x
dcl_output_siv o0.x, finalTriUeq0EdgeTessFactor
dcl_output_siv o1.x, finalTriVeq0EdgeTessFactor
dcl_output_siv o2.x, finalTriWeq0EdgeTessFactor
dcl_temps 1
dcl_indexrange o0.x 3
iadd r0.x, vForkInstanceID.x, l(1)
udiv null, r0.x, r0.x, l(3)
mov r0.y, vForkInstanceID.x
mov o[r0.y + 0].x, vicp[r0.x + 0][0].x
ret 
hs_fork_phase 
dcl_input vicp[3][0].x
dcl_output_siv o3.x, finalTriInsideTessFactor
dcl_temps 1
min r0.x, vicp[2][0].x, vicp[1][0].x
min o3.x, r0.x, vicp[0][0].x
ret 
// Approximately 0 instruction slots used
#endif

const BYTE adaptive_triangle_hs[] =
{
     68,  88,  66,  67, 140,  36, 
    161,  63,  15,   0,   6,  98, 
     51, 227, 112, 172,   7, 160, 
    168, 204,   1,   0,   0,   0, 
    128,   3,   0,   0,   4,   0, 
      0,   0,  48,   0,   0,   0, 
    104,   0,   0,   0, 156,   0, 
      0,   0,  48,   1,   0,   0, 
     73,  83,  71,  78,  48,   0, 
      0,   0,   1,   0,   0,   0, 
      8,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   1,   0,   0,  88,  69, 
     84,  69,  83,  83,  70,  65, 
     67,  84,  79,  82,   0, 171, 
    171, 171,  79,  83,  71,  78, 
     44,   0,   0,   0,   1,   0, 
      0,   0,   8,   0,   0,   0, 
     32,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   1,  14,   0,   0, 
     88,  69,  86,  69,  82,  84, 
     69,  88,  73,  68,   0, 171, 
     80,  67,  83,  71, 140,   0, 
      0,   0,   4,   0,   0,   0, 
      8,   0,   0,   0, 104,   0, 
      0,   0,   0,   0,   0,   0, 
     13,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      1,  14,   0,   0, 104,   0, 
      0,   0,   1,   0,   0,   0, 
     13,   0,   0,   0,   3,   0, 
      0,   0,   1,   0,   0,   0, 
      1,  14,   0,   0, 104,   0, 
      0,   0,   2,   0,   0,   0, 
     13,   0,   0,   0,   3,   0, 
      0,   0,   2,   0,   0,   0, 
      1,  14,   0,   0, 118,   0, 
      0,   0,   0,   0,   0,   0, 
     14,   0,   0,   0,   3,   0, 
      0,   0,   3,   0,   0,   0, 
      1,  14,   0,   0,  83,  86, 
     95,  84, 101, 115, 115,  70, 
     97,  99, 116, 111, 114,   0, 
     83,  86,  95,  73, 110, 115, 
    105, 100, 101,  84, 101, 115, 
    115,  70,  97,  99, 116, 111, 
    114,   0, 171, 171,  83,  72, 
     69,  88,  72,   2,   0,   0, 
     81,   0,   3,   0, 146,   0, 
      0,   0, 113,   0,   0,   1, 
    147,  24,   0,   1, 148,   8, 
      0,   1, 149,  16,   0,   1, 
    150,  32,   0,   1, 151,  24, 
      0,   1, 106,   8,   0,   1, 
     89,   0,   0,   7,  70, 142, 
     48,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   2,   0,   0,   0, 
      0,   0,   0,   0, 114,   0, 
      0,   1,  95,   0,   0,   2, 
      0, 176,   0,   0, 101,   0, 
      0,   3,  18,  32,  16,   0, 
      0,   0,   0,   0, 104,   0, 
      0,   2,   1,   0,   0,   0, 
     30,   0,   0,   8,  18,   0, 
     16,   0,   0,   0,   0,   0, 
      1, 176,   0,   0,  26, 128, 
     48,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   1,   0,   0,   7, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   1,  64, 
      0,   0, 255, 255, 255,   0, 
     83,   0,   0,   9,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  42, 128,  48,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     84,   0,   0,   9,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  58, 128,  48,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   1,   0,   0,   0, 
     86,   0,   0,   5,  18,  32, 
     16,   0,   0,   0,   0,   0, 
     10,   0,  16,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
    115,   0,   0,   1, 153,   0, 
      0,   2,   3,   0,   0,   0, 
     95,   0,   0,   2,   0, 112, 
      1,   0,  95,   0,   0,   4, 
     18, 144,  33,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
    103,   0,   0,   4,  18,  32, 
     16,   0,   0,   0,   0,   0, 
     17,   0,   0,   0, 103,   0, 
      0,   4,  18,  32,  16,   0, 
      1,   0,   0,   0,  18,   0, 
      0,   0, 103,   0,   0,   4, 
     18,  32,  16,   0,   2,   0, 
      0,   0,  19,   0,   0,   0, 
    104,   0,   0,   2,   1,   0, 
      0,   0,  91,   0,   0,   4, 
     18,  32,  16,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
     30,   0,   0,   6,  18,   0, 
     16,   0,   0,   0,   0,   0, 
     10, 112,   1,   0,   1,  64, 
      0,   0,   1,   0,   0,   0, 
     78,   0,   0,   8,   0, 208, 
      0,   0,  18,   0,  16,   0, 
      0,   0,   0,   0,  10,   0, 
     16,   0,   0,   0,   0,   0, 
      1,  64,   0,   0,   3,   0, 
      0,   0,  54,   0,   0,   4, 
     34,   0,  16,   0,   0,   0, 
      0,   0,  10, 112,   1,   0, 
     54,   0,   0,   8,  18,  32, 
    144,   0,  26,   0,  16,   0, 
      0,   0,   0,   0,  10, 144, 
    161,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
    115,   0,   0,   1,  95,   0, 
      0,   4,  18, 144,  33,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0, 103,   0,   0,   4, 
     18,  32,  16,   0,   3,   0, 
      0,   0,  20,   0,   0,   0, 
    104,   0,   0,   2,   1,   0, 
      0,   0,  51,   0,   0,   9, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10, 144,  33,   0, 
      2,   0,   0,   0,   0,   0, 
      0,   0,  10, 144,  33,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0,  51,   0,   0,   8, 
     18,  32,  16,   0,   3,   0, 
      0,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  10, 144, 
     33,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,  62,   0, 
      0,   1
};
