#if 0
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Patch Constant signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TessFactor            0   x           0  TRIEDGE   float   x   
// SV_TessFactor            1   x           1  TRIEDGE   float   x   
// SV_TessFactor            2   x           2  TRIEDGE   float   x   
// SV_InsideTessFactor      0   x           3   TRIINT   float   x   
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// XEVERTEXID               0   x           0     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// XEVERTEXID               0   x           0     NONE   float   x   
//
hs_5_1
hs_decls 
dcl_input_control_point_count 1
dcl_output_control_point_count 1
dcl_tessellator_domain domain_tri
dcl_tessellator_partitioning partitioning_integer
dcl_tessellator_output_primitive output_triangle_cw
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[0:0][1], immediateIndexed, space=0
hs_control_point_phase 
dcl_input v[1][0].x
dcl_output o0.x
mov o0.x, v[0][0].x
ret 
hs_fork_phase 
dcl_hs_fork_phase_instance_count 3
dcl_input vForkInstanceID
dcl_output_siv o0.x, finalTriUeq0EdgeTessFactor
dcl_output_siv o1.x, finalTriVeq0EdgeTessFactor
dcl_output_siv o2.x, finalTriWeq0EdgeTessFactor
dcl_temps 1
dcl_indexrange o0.x 3
mov r0.x, vForkInstanceID.x
mov o[r0.x + 0].x, CB0[0][0].z
ret 
hs_fork_phase 
dcl_output_siv o3.x, finalTriInsideTessFactor
mov o3.x, CB0[0][0].z
ret 
// Approximately 0 instruction slots used
#endif

const BYTE discrete_triangle_1cp_hs[] =
{
     68,  88,  66,  67,  39, 187, 
    156,  77,  87,  23, 142, 175, 
     26,  11, 164, 148, 127, 232, 
    124, 142,   1,   0,   0,   0, 
    116,   2,   0,   0,   4,   0, 
      0,   0,  48,   0,   0,   0, 
    100,   0,   0,   0, 152,   0, 
      0,   0,  44,   1,   0,   0, 
     73,  83,  71,  78,  44,   0, 
      0,   0,   1,   0,   0,   0, 
      8,   0,   0,   0,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,   0,   0,   0,   0, 
      1,   1,   0,   0,  88,  69, 
     86,  69,  82,  84,  69,  88, 
     73,  68,   0, 171,  79,  83, 
     71,  78,  44,   0,   0,   0, 
      1,   0,   0,   0,   8,   0, 
      0,   0,  32,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   3,   0,   0,   0, 
      0,   0,   0,   0,   1,  14, 
      0,   0,  88,  69,  86,  69, 
     82,  84,  69,  88,  73,  68, 
      0, 171,  80,  67,  83,  71, 
    140,   0,   0,   0,   4,   0, 
      0,   0,   8,   0,   0,   0, 
    104,   0,   0,   0,   0,   0, 
      0,   0,  13,   0,   0,   0, 
      3,   0,   0,   0,   0,   0, 
      0,   0,   1,  14,   0,   0, 
    104,   0,   0,   0,   1,   0, 
      0,   0,  13,   0,   0,   0, 
      3,   0,   0,   0,   1,   0, 
      0,   0,   1,  14,   0,   0, 
    104,   0,   0,   0,   2,   0, 
      0,   0,  13,   0,   0,   0, 
      3,   0,   0,   0,   2,   0, 
      0,   0,   1,  14,   0,   0, 
    118,   0,   0,   0,   0,   0, 
      0,   0,  14,   0,   0,   0, 
      3,   0,   0,   0,   3,   0, 
      0,   0,   1,  14,   0,   0, 
     83,  86,  95,  84, 101, 115, 
    115,  70,  97,  99, 116, 111, 
    114,   0,  83,  86,  95,  73, 
    110, 115, 105, 100, 101,  84, 
    101, 115, 115,  70,  97,  99, 
    116, 111, 114,   0, 171, 171, 
     83,  72,  69,  88,  64,   1, 
      0,   0,  81,   0,   3,   0, 
     80,   0,   0,   0, 113,   0, 
      0,   1, 147,   8,   0,   1, 
    148,   8,   0,   1, 149,  16, 
      0,   1, 150,   8,   0,   1, 
    151,  24,   0,   1, 106,   8, 
      0,   1,  89,   0,   0,   7, 
     70, 142,  48,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   1,   0, 
      0,   0,   0,   0,   0,   0, 
    114,   0,   0,   1,  95,   0, 
      0,   4,  18,  16,  32,   0, 
      1,   0,   0,   0,   0,   0, 
      0,   0, 101,   0,   0,   3, 
     18,  32,  16,   0,   0,   0, 
      0,   0,  54,   0,   0,   6, 
     18,  32,  16,   0,   0,   0, 
      0,   0,  10,  16,  32,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
    115,   0,   0,   1, 153,   0, 
      0,   2,   3,   0,   0,   0, 
     95,   0,   0,   2,   0, 112, 
      1,   0, 103,   0,   0,   4, 
     18,  32,  16,   0,   0,   0, 
      0,   0,  17,   0,   0,   0, 
    103,   0,   0,   4,  18,  32, 
     16,   0,   1,   0,   0,   0, 
     18,   0,   0,   0, 103,   0, 
      0,   4,  18,  32,  16,   0, 
      2,   0,   0,   0,  19,   0, 
      0,   0, 104,   0,   0,   2, 
      1,   0,   0,   0,  91,   0, 
      0,   4,  18,  32,  16,   0, 
      0,   0,   0,   0,   3,   0, 
      0,   0,  54,   0,   0,   4, 
     18,   0,  16,   0,   0,   0, 
      0,   0,  10, 112,   1,   0, 
     54,   0,   0,   8,  18,  32, 
    144,   0,  10,   0,  16,   0, 
      0,   0,   0,   0,  42, 128, 
     48,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,  62,   0,   0,   1, 
    115,   0,   0,   1, 103,   0, 
      0,   4,  18,  32,  16,   0, 
      3,   0,   0,   0,  20,   0, 
      0,   0,  54,   0,   0,   7, 
     18,  32,  16,   0,   3,   0, 
      0,   0,  42, 128,  48,   0, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   0,   0,   0, 
     62,   0,   0,   1
};
